CREATE TABLE DATABASECHANGELOG
(
    ID VARCHAR(63) NOT NULL,
    AUTHOR VARCHAR(63) NOT NULL,
    FILENAME VARCHAR(200) NOT NULL,
    DATEEXECUTED DATETIME NOT NULL,
    ORDEREXECUTED INT NOT NULL,
    EXECTYPE VARCHAR(10) NOT NULL,
    MD5SUM VARCHAR(35),
    DESCRIPTION VARCHAR(255),
    COMMENTS VARCHAR(255),
    TAG VARCHAR(255),
    LIQUIBASE VARCHAR(20),
    PRIMARY KEY (ID, AUTHOR, FILENAME)
);
CREATE TABLE DATABASECHANGELOGLOCK
(
    ID INT PRIMARY KEY NOT NULL,
    LOCKED TINYINT NOT NULL,
    LOCKGRANTED DATETIME,
    LOCKEDBY VARCHAR(255)
);
