INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (1, null, true, 'Patient History');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (2, null, true, 'Physical examination report');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (3, null, true, 'Consultation report');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (4, null, true, 'Operative report');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (5, null, true, 'Radiology report');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (6, null, true, 'Pathology report');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (7, null, true, 'Laboratory report');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (8, null, true, 'Emergency report');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (9, null, true, 'SOAP note report (progress report)');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (10, null, true, 'Progress note report');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (11, null, true, 'Therapy report');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (12, null, true, 'Clinical notes');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (13, null, true, 'Autopsy reports');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (14, null, true, 'Biopsy reports');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (15, null, true, 'Psychiatric observations');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (16, null, true, 'X-ray reports');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (17, null, true, 'Scan reports');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (18, null, true, 'Referral letters');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (19, null, true, 'Daily reports');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (20, null, true, 'Discharge summaries');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (21, null, true, 'Medical Prescription');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (22, null, true, 'Doctor Notes');
INSERT INTO vellkare.medical_record_type (id, description, enabled, name) VALUES (23, null, true, 'Other');
